name = "Common"
uuid = "ba1b9109-165e-4adc-93bb-3841bfa11de7"
authors = ["Jonnie Diegelman <jonniediegelman@gmail.com>"]
version = "0.1.0"

[deps]
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
